"""lessons_per_week qoshildi, price_per_lesson olib tashlandi

Revision ID: 497d75d116b6
Revises: 7a9a275d8d2c
Create Date: 2026-08-24 00:41:22.500129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497d75d116b6'
down_revision: Union[str, None] = '7a9a275d8d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('lessons_per_week', sa.Integer(), nullable=True))
    op.execute("UPDATE courses SET lessons_per_week = 2 WHERE lessons_per_week IS NULL")
    op.alter_column('courses', 'lessons_per_week', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('price_per_lesson', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('courses', 'lessons_per_week')
    # ### end Alembic commands ###
