"""sync_models

Revision ID: d5e2da21e529
Revises: 497d75d116b6
Create Date: 2026-08-28 16:09:19.961055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5e2da21e529'
down_revision: Union[str, None] = '497d75d116b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure enum types exist
    testsourceenum = postgresql.ENUM('manual', 'ai_pdf', name='testsourceenum')
    testsourceenum.create(op.get_bind(), checkfirst=True)
    
    coursetypeenum = postgresql.ENUM('IELTS', 'CEFR', 'General', name='coursetypeenum')
    coursetypeenum.create(op.get_bind(), checkfirst=True)

    enrollmentstatusenum = postgresql.ENUM('active', 'waiting', 'completed', 'dropped', name='enrollmentstatusenum')
    enrollmentstatusenum.create(op.get_bind(), checkfirst=True)

    op.alter_column('courses', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('IELTS', 'CEFR', 'General', name='coursetypeenum'),
               postgresql_using="type::coursetypeenum",
               existing_nullable=False)
    op.alter_column('courses', 'price_per_lesson',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('enrollments', sa.Column('free_trial_id', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('status', sa.Enum('active', 'waiting', 'completed', 'dropped', name='enrollmentstatusenum'), server_default='active', nullable=False))
    op.add_column('enrollments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'free_trial_requests', ['free_trial_id'], ['id'])
    op.add_column('homeworks', sa.Column('lesson_date', sa.Date(), nullable=True))
    op.add_column('homeworks', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('payments', sa.Column('enrollment_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'payments', 'enrollments', ['enrollment_id'], ['id'])
    op.add_column('referral_bonuses', sa.Column('bonus_percent', sa.Numeric(precision=5, scale=2), server_default='10.0', nullable=False))
    op.add_column('referral_bonuses', sa.Column('applied_month', sa.Date(), nullable=True))
    op.add_column('referral_bonuses', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.drop_column('referral_bonuses', 'percent')
    op.add_column('refunds', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('refunds', sa.Column('requested_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('refunds', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'refunds', 'payments', ['payment_id'], ['id'])
    op.drop_column('refunds', 'created_at')
    op.add_column('test_results', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('time_limit_min', sa.Integer(), server_default='20', nullable=False))
    op.add_column('tests', sa.Column('source', sa.Enum('manual', 'ai_pdf', name='testsourceenum'), server_default='manual', nullable=False))
    op.alter_column('tests', 'teacher_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('waiting_list', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('waiting_list', sa.Column('requested_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('waiting_list', sa.Column('notified', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('waiting_list', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waiting_list', 'level',
               existing_type=postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='levelenum'),
               nullable=True)
    op.create_foreign_key(None, 'waiting_list', 'groups', ['group_id'], ['id'])
    op.drop_column('waiting_list', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiting_list', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'waiting_list', type_='foreignkey')
    op.alter_column('waiting_list', 'level',
               existing_type=postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='levelenum'),
               nullable=False)
    op.alter_column('waiting_list', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('waiting_list', 'notified')
    op.drop_column('waiting_list', 'requested_at')
    op.drop_column('waiting_list', 'group_id')
    op.alter_column('tests', 'teacher_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('tests', 'source')
    op.drop_column('tests', 'time_limit_min')
    op.drop_column('test_results', 'max_score')
    op.add_column('refunds', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.drop_column('refunds', 'processed_at')
    op.drop_column('refunds', 'requested_at')
    op.drop_column('refunds', 'payment_id')
    op.add_column('referral_bonuses', sa.Column('percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_column('referral_bonuses', 'status')
    op.drop_column('referral_bonuses', 'applied_month')
    op.drop_column('referral_bonuses', 'bonus_percent')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'note')
    op.drop_column('payments', 'enrollment_id')
    op.drop_column('homeworks', 'reminder_sent')
    op.drop_column('homeworks', 'lesson_date')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'completed_at')
    op.drop_column('enrollments', 'status')
    op.drop_column('enrollments', 'free_trial_id')
    op.alter_column('courses', 'price_per_lesson',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('courses', 'type',
               existing_type=sa.Enum('IELTS', 'CEFR', 'General', name='coursetypeenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
